name: Build and Deploy
on:
  push:
    branches: [main]

# Grants the virtual runner permission to write the build to a new branch
permissions:
  contents: write
  pages: write
  id-token: write

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout 🛎️
        uses: actions/checkout@v4

      - name: Setup Node 🟢
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Clean Install & Build 🔧
        run: |
          npm install --frozen-lockfile || npm install
          npx vite build

      - name: Deploy 🚀
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: dist
          branch: gh-pages
