name: Build and Deploy
on:
  push:
    branches: [main]

# THIS BLOCK TELLS GITHUB TO GIVE PERMISSION AUTOMATICALLY
permissions:
  contents: write
  pages: write
  id-token: write

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    env:
      FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true
    steps:
      - name: Checkout 🛎️
        uses: actions/checkout@v4

      - name: Setup Node 🟢
        uses: actions/setup-node@v4
        with:
          node-version: 24
          cache: 'npm'

      - name: Install & Build 🔧
        run: |
          npm install
          npx vite build

      - name: Deploy 🚀
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: dist
          branch: gh-pages
